### ISSUE TITLE
On unfix length labels

### ISSUE THREAD

**Issue by tengpeng** [jimxinbo/multilabel-layer-mxnet#1]
Suppose the label lengths varies. Is it a good idea to encode each label to dummy variable, that is 0-1?

**Comment by tengpeng** [comment]
Oh, I just managed to read the entire issue on mxnet. Now, I understand what is going on. 

Close. Thanks.

**Comment by jimxinbo** [comment]
Thanks for the interest. 

This code was originally designed for problems where k<<K. So the current one save some space.

**Comment by jimxinbo** [comment]
Anyway, using dummy variables is neat in math and could be easily modified from the current code.
